name: Bug Report
description: Create a report to help us improve
title: "Bug Report: "
labels: [bug]
# This template is inspired by templates in https://github.com/dotnet/runtime
body:
  - type: markdown
    attributes:
      value: Thank you for investing your time on improving this project! Please fill out the forms below to the best of your ability.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        - Please share a clear and concise description of the problem.
        - Include minimal steps to reproduce the problem if possible.
        - What behavior are you seeing, and what behavior would you expect?
    validations:
      required: true
  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: |
        - Which version of the program are you running?
        - What OS and version?
        - Do you know whether it is specific to your particular configuration?
    validations:
      required: false
  - type: textarea
    id: regression
    attributes:
      label: Regression?
      description: Did this work in a previous release? If you can try a previous release to find out, that can help us narrow down the problem. If you don't know, that's OK.
    validations:
      required: false
  - type: textarea
    id: additionals
    attributes:
      label: Other Information
      description: |
        - Please include any relevant stack traces or error messages. If possible please include text as text rather than images (so it shows up in searches).
        - If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
        - Do you know of any workarounds?
    validations:
      required: false
