name: Feature Request
description: Suggest an idea for this project
title: "Feature Request: "
labels: [feature-request]
# This template is inspired by templates in https://github.com/dotnet/runtime
body:
  - type: markdown
    attributes:
      value: Thank you for investing your time on improving this project! Please fill out the forms below to the best of your ability.
  - type: textarea
    id: feature-problem
    attributes:
      label: Feature or Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.   
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.     
    validations:
      required: false
  - type: textarea
    id: additionals
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context
    validations:
      required: false
