name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src -c Release --no-restore

      - name: Test
        run: dotnet test ./src -c Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Run HostsParser
        run: |
          cd ./src/HostsParser/bin/Release/net6.0/
          dotnet HostsParser.dll

      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
          fail_ci_if_error: true