name: Publish Filter

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true

    - name: Run build.sh
      run: ./build.sh
 
    - name: Run HostsParser
      run: |
        cd ./artifacts
        dotnet HostsParser.dll

    - name: Copy filter to public directory
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir ./public
        FILTER=./artifacts/filter.txt
        cp $FILTER ./public
        cp $FILTER ./public/hosts

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: ${{ github.event.head_commit.message }}