name: Build / Publish Hosts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore
    
    - name: Run HostsParser
      run: |
        cd bin/Release/net5.0
        dotnet HostsParser.dll

    - name: Copy hosts to root of branch
      run: |
        mkdir ./public
        HOSTS=bin/Release/net5.0/hosts
        if test -f "$HOSTS"; then
            cp $HOSTS ./public
        fi

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public